### ISSUE TITLE
Compatibility with Synthesia 

### ISSUE THREAD

**Issue by andre2007** [serifpersia/pianolux-esp32#7]
Your project sounds really interesting. I am not sure whether I understand it correctly. Can I use it together with the piano training software Synthesia (https://www.synthesiagame.com/) to show the keys which should be played?
Synthesia in general supports luminous keys, but is it possible together with your project?

**Comment by serifpersia** [comment]
No the project is for live playing/recording. Users can use USB/RTP or BLE MIDI to translate midi messages to LEDs. The project supports MIDI out via RTP MIDI so you could use the USB or BLE MIDI input midi messages(note on, note off and 3 main pedal cc messages)  on your PC or any RTPMIDI capable device. Learn with leds is not focus of this project, my arduino version does have wip learn mode but that never got finished since the developer who tried to do that didn't finish that feature. 

So no, there is no support for this or is it planned in the future by my end. Feel free to create new issues if have problems with the functions of the project, and or if you are developer you welcome to implement and do a PR. Every feature of the project is documented on repo's README and YouTube showcase videos look it up on YouTube channel @PianoLux99 and read README for all information about the project. 

I'm closing this.
